### ISSUE TITLE
FastDeserializerGenerator throws NPE for avro schemas with nested records 

### ISSUE THREAD

**Issue by rebelcodr** [RTBHOUSE/avro-fastserde#1]
For avro schemas with nested records structure, FastDeserializerGenerator.generateDeserializer throws NPE if FastGenericDatumReader is used with a (reader) schema different from the writer schema. It deserializes correctly if both writer and reader schemas are the same.

Sample writer schema (a record with 3 nested records):
{
  "type": "record",
  "name": "User",
  "namespace": "example.avro",
  "fields": [
    {
      "name": "address",
      "type": {
        "type": "record",
        "name": "address_data",
        "fields": [
          {
            "name": "streetName",
            "type": "string",
            "doc": "name of street"
          },
          {
            "name": "city",
            "type": "string",
            "doc": "name of city"
          }
        ]
      },
      "doc": "user addresses"
    },
    {
      "name": "segment",
      "type": {
        "type": "record",
        "name": "segment_data",
        "fields": [
          {
            "name": "segmentA",
            "type": "string",
            "doc": "name of segment A"
          },
          {
            "name": "segmentB",
            "type": "string",
            "doc": "name of segment B"
          }
        ]
      },
      "doc": "user segments"
    },
    {
      "name": "devices",
      "type": {
        "type": "record",
        "name": "device_data",
        "fields": [
          {
            "name": "deviceA",
            "type": "string",
            "doc": "name of device A"
          },
          {
            "name": "deviceB",
            "type": "string",
            "doc": "name of device B"
          }
        ]
      },
      "doc": "user devices"
    }
  ],
  "doc": "user schema"
}

Sample reader schema (contains one less record than the writer):
{
  "type": "record",
  "name": "User",
  "namespace": "example.avro",
  "fields": [
    {
      "name": "address",
      "type": {
        "type": "record",
        "name": "address_data",
        "fields": [
          {
            "name": "streetName",
            "type": "string",
            "doc": "name of street"
          },
          {
            "name": "city",
            "type": "string",
            "doc": "name of city"
          }
        ]
      },
      "doc": "user addresses"
    },
    {
      "name": "devices",
      "type": {
        "type": "record",
        "name": "device_data",
        "fields": [
          {
            "name": "deviceA",
            "type": "string",
            "doc": "name of device A"
          },
          {
            "name": "deviceB",
            "type": "string",
            "doc": "name of device B"
          }
        ]
      },
      "doc": "user devices"
    }
  ],
  "doc": "user schema"
}

WARNING: deserializer generation exception
com.rtbhouse.utils.avro.FastDeserializerGeneratorException: java.lang.NullPointerException
	at com.rtbhouse.utils.avro.FastDeserializerGenerator.generateDeserializer(FastDeserializerGenerator.java:169)
	at com.rtbhouse.utils.avro.FastSerdeCache.buildGenericDeserializer(FastSerdeCache.java:322)
	at com.rtbhouse.utils.avro.FastSerdeCache.lambda$getFastGenericDeserializer$4(FastSerdeCache.java:225)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.rtbhouse.utils.avro.FastDeserializerGenerator.processRecord(FastDeserializerGenerator.java:227)
	at com.rtbhouse.utils.avro.FastDeserializerGenerator.generateDeserializer(FastDeserializerGenerator.java:97)
	... 6 more

**Comment by flowenol** [comment]
Hi,

Thanks for posting this issue. It turned out to be a problem with ResolvingGrammarGeneartor symbol handling. I have already committed a fix regarding this issue, so please check the latest 1.0.1-SNAPSHOT version. Once you confirm it's ok, I'll prepare a 1.0.1 release.

**Comment by rebelcodr** [comment]
Thank you, I will test it out and let you know soon.

**Comment by flowenol** [comment]
This bug has been fixed in 1.0.1 release.
