### ISSUE TITLE
Support StringableClasses

### ISSUE THREAD

**Issue by michaelandrepearce** [RTBHOUSE/avro-fastserde#3]
Please could this support StringableClasses, currently it throws a cast exception, where these are defined in avro schema.

e.g.

`            {
              "name": "id",
              "type": {
                "type": "string",
                "java-class": "java.math.BigInteger"
              }
            }
` 

https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/specific/SpecificData.java

/** Read/write some common builtin classes as strings.  Representing these as
   * strings isn't always best, as they aren't always ordered ideally, but at
   * least they're stored.  Also note that, for compatibility, only classes
   * that wouldn't be otherwise correctly readable or writable should be added
   * here, e.g., those without a no-arg constructor or those whose fields are
   * all transient. */
  protected Set<Class> stringableClasses = new HashSet<>();
  {
    stringableClasses.add(java.math.BigDecimal.class);
    stringableClasses.add(java.math.BigInteger.class);
    stringableClasses.add(java.net.URI.class);
    stringableClasses.add(java.net.URL.class);
    stringableClasses.add(java.io.File.class);
  }

**Comment by flowenol** [comment]
The implementation of this feature is on its way, we plan to release next week.

**Comment by michaelandrepearce** [comment]
Wow great stuff !! Thank you.

**Comment by flowenol** [comment]
Hi,

Check for the newest release - version 1.0.2. A little bit late than expected, but it should implement this feature. Waiting for your input to close this issue.

**Comment by michaelandrepearce** [comment]
@flowenol looks like it works, have tested the original case / schema it didn't and it seems to be working fine now.

Thanks for this.
