### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by michaelandrepearce** [RTBHOUSE/avro-fastserde#4]
Hi 

Could you possibly update the project with a LICENSE file, so it clarifies what license this can be used under e.g. MIT, BSD-3-Clause, or Apache License 2.0

we notice some of you other projects have this (but seems sometime MIT is used and other times ASLv2)
https://github.com/RTBHOUSE/graphite-gw/blob/master/LICENSE
https://github.com/RTBHOUSE/torch-utils/blob/master/LICENSE

thanks.
Mike

(im asking as i want to add a dependency to use this over the vanilla avro serializer in an apache licensed open source project, but to add this its important all dependencies in it have a License and the license is ASL compatible (the ones i mentioned are))

**Comment by DJRickyB** [comment]
yes please! would love to use/contribute if you're open to apache or similar.  otherwise we can't use it here

**Comment by flowenol** [comment]
Hi, if GPLv3 doesn't suit you then we are willing to change to Apache. As a matter of fact, we intend to make the project as freely available as possible, of course without any liabilities.

**Comment by michaelandrepearce** [comment]
Apache license would be best if you wouldn't mind. 

GPLv3 is too restrive unfortunatly, we wouldn't be able to use this as a dependency in a apache license project. https://www.apache.org/licenses/GPL-compatibility.html

**Comment by flowenol** [comment]
The license has been changed to Apache 2.0 upon your request.

**Comment by flowenol** [comment]
Properly licensed release will appear in a few days.

**Comment by flowenol** [comment]
Hi,

A properly licensed release is available since today, so I am closing this issue.

**Comment by michaelandrepearce** [comment]
@flowenol, FYI as im sure you'd like to know place where it is being used,

I am looking to contribute/commit this to the following project:
https://github.com/hortonworks/registry

Issue: https://github.com/hortonworks/registry/issues/455, 
PR: https://github.com/hortonworks/registry/pull/456
